# Generated by Django 2.2.4 on 2019-09-02 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a car brand (e.g. Toyota)', max_length=200)),
                ('logo', models.ImageField(help_text='Upload brand logo', upload_to='media/images/logos')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(help_text='Enter price of the car')),
                ('summary', models.TextField(help_text='Enter a brief description of the car', max_length=1000)),
                ('photo', models.ImageField(help_text='Upload the image of the car', upload_to='media/photos/cars')),
                ('brand', models.ForeignKey(help_text='Enter the specific model of the car', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineshop.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular car across whole shop', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('s', 'Sold Out')], default='s', help_text='Car availability', max_length=1)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineshop.Car')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
