# Generated by Django 2.2.4 on 2019-09-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstance',
            new_name='CarInstance',
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(help_text='Upload the image of the car', upload_to='media/images/cars'),
        ),
    ]
