# Generated by Django 2.2.4 on 2019-09-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_auto_20190902_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='CarBrand',
        ),
        migrations.RenameModel(
            old_name='Car',
            new_name='CarModel',
        ),
        migrations.RenameModel(
            old_name='CarInstance',
            new_name='CarModelInstance',
        ),
    ]
